version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-test_k8s}
      POSTGRES_USER: ${POSTGRES_USER-test_k8s}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "0.0.0.0:5432:5432"
    command: postgres -c listen_addresses='*' -c port=5432

volumes:
  db_data: